spring:
  application:
    name: customer-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka/
  instance:
    hostname: localhost