spring:
  application:
    name: db-customer

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://ims-discovery-server.herokuapp.com/eureka/
  instance:
    hostname: ims-discovery-server.herokuapp.com
    homePageUrl: https://ims-customer-service.herokuapp.com/
    statusPageUrl: https://ims-customer-service.herokuapp.com/actuator/info
    healthCheckUrl: https://ims-customer-service.herokuapp.com/actuator/health